"""Production authentication contracts and API token primitives."""

from public_agent.auth.base import (
    APIPrincipalRecord,
    AuthenticatedPrincipal,
    AuthenticationError,
    IssuedAPIToken,
    PrincipalCreateRequest,
    PrincipalStatus,
)
from public_agent.auth.management import (
    AUTH_AUDIT_READ,
    AUTH_MANAGEMENT_PERMISSIONS,
    AUTH_PRINCIPALS_READ,
    AUTH_PRINCIPALS_WRITE,
    AUTH_TOKENS_ISSUE,
    AUTH_TOKENS_READ,
    AUTH_TOKENS_REVOKE,
    CRITICAL_AUTH_PERMISSIONS,
    DEFAULT_MANAGEABLE_PERMISSIONS,
    APITokenSummary,
    AuthCursorError,
    AuthenticationAuditOutcome,
    AuthenticationAuditPage,
    AuthenticationAuditQuery,
    AuthenticationAuditRecord,
    AuthManagementAuthorizationError,
    AuthStateConflictError,
    ManagedPrincipalCreateRequest,
    PrincipalManagementPage,
    PrincipalManagementQuery,
    TokenManagementPage,
    TokenManagementQuery,
)
from public_agent.auth.tokens import APITokenCodec

__all__ = [
    "AUTH_AUDIT_READ",
    "AUTH_MANAGEMENT_PERMISSIONS",
    "AUTH_PRINCIPALS_READ",
    "AUTH_PRINCIPALS_WRITE",
    "AUTH_TOKENS_ISSUE",
    "AUTH_TOKENS_READ",
    "AUTH_TOKENS_REVOKE",
    "CRITICAL_AUTH_PERMISSIONS",
    "DEFAULT_MANAGEABLE_PERMISSIONS",
    "APIPrincipalRecord",
    "APITokenCodec",
    "APITokenSummary",
    "AuthCursorError",
    "AuthManagementAuthorizationError",
    "AuthStateConflictError",
    "AuthenticatedPrincipal",
    "AuthenticationAuditOutcome",
    "AuthenticationAuditPage",
    "AuthenticationAuditQuery",
    "AuthenticationAuditRecord",
    "AuthenticationError",
    "IssuedAPIToken",
    "ManagedPrincipalCreateRequest",
    "PrincipalCreateRequest",
    "PrincipalManagementPage",
    "PrincipalManagementQuery",
    "PrincipalStatus",
    "TokenManagementPage",
    "TokenManagementQuery",
]
